### PR TITLE
Document basic aconcli usage

### LINKED ISSUE #1: [Doc] Broken link in aconcli README
https://github.com/intel/ACON/blob/e0b78f530fce06f984e62ebec76fa6b16d8a6d77/aconcli/README.md?plain=1#L23 refers to an intel internal link for Utility.md, so I thought it is just a minor issue to fix the link to external (this) repo,, but, I could not find the file even in the internal repo.

Could you also review all the other links to make sure we are good?

@binxing @xxu36

### PR DESCRIPTION
**Pull request by dcmiddle**
fixes #1

### CODE REVIEW

**Comment by dcmiddle** [comment]
cc: @ svenkata9

**Comment by svenkata9** [comment]
> cc: @ svenkata9

Looks good to me. (PS: @dcmiddle You have a space between @ and myid, so I didn't get the notification. I checked randomly the PRs and found this one).

**Comment by dcmiddle** [comment]
sorry @svenkata9! glad you saw the PR despite my typo.
We can discuss plugins separately .. I don't want to go off topic on this thread.

**Comment by binxing** [comment]
@xxu36 will add more details on command usages in the form of help messages of `aconcli`.

**Pull request merged**
