### PR TITLE
aconcli: Remove broken link in aconcli README

### PR DESCRIPTION
**Pull request by xxu36**
Fix issue #1

### CODE REVIEW

**Comment by dcmiddle** [comment]
@xxu36 where did this CLI documentation move to though? I don't see it in the existing docs I read through. Was it intentionally removed or accidentally lost during the repo reorganization?

**Comment by xxu36** [comment]
> @xxu36 where did this CLI documentation move to though? I don't see it in the existing docs I read through. Was it intentionally removed or accidentally lost during the repo reorganization?

@dcmiddle I think previously we had CLI documentation under `doc` directory. Before we made the repo public we submitted a commit to remove several immature docs which included the CLI doc. I think I can upload the updated CLI doc in a new commit.

**Comment by svenkata9** [comment]
@xxu36 Can we fix that as part of this PR itself - add the CLI doc and update the link?

**Comment by xxu36** [comment]
@svenkata9 Makes sense. Then I will update this PR directly once the doc is ready.

**Comment by binxing** [comment]
`aconcli` is under active development so it's hard to maintain a user manual that always matches the code. Let's put more details in `aconcli`'s help messages and use a `QuickStart.md` to give users an orientation on what should be done and in what order.

**Comment by dcmiddle** [comment]
closed in favor of #5.

**Pull request closed without merging**
